"""Exercises the real Alembic migration chain end-to-end.

tests/conftest.py builds the schema every other test file runs against via
Base.metadata.create_all — convenient, but it means the migration chain a
real deployment actually runs (`alembic upgrade head`) is never itself
exercised by any test. This file runs that exact chain against a scratch
database and confirms the result has no drift against koshi.db.Base's
models, using alembic.command.check (which raises
AutogenerateDiffsDetected if autogenerate would still have pending ops —
i.e. the migrated schema disagrees with the models).

Uses a dedicated `koshi_migration_test` database, created and dropped by
this file's own fixture, rather than koshi_test — koshi_test is built by
tests/conftest.py's session-scoped `engine` fixture via create_all/drop_all
and reused (with per-test row deletes) by every other test file, so
running a separate migration chain against it, or dropping/recreating it
mid-session, risks corrupting or racing those other tests' state.
"""

import os
from pathlib import Path

import pytest
import sqlalchemy
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

REPO_ROOT = Path(__file__).parent.parent
ALEMBIC_INI = REPO_ROOT / "alembic.ini"
ALEMBIC_SCRIPT_LOCATION = REPO_ROOT / "alembic"

ADMIN_DATABASE_URL = os.environ.get(
    "MIGRATION_TEST_ADMIN_DATABASE_URL",
    "postgresql+psycopg://koshi:koshi@localhost:5432/postgres",
)
MIGRATION_TEST_DB_NAME = "koshi_migration_test"
MIGRATION_TEST_DATABASE_URL = os.environ.get(
    "MIGRATION_TEST_DATABASE_URL",
    f"postgresql+psycopg://koshi:koshi@localhost:5432/{MIGRATION_TEST_DB_NAME}",
)


def _drop_and_create_migration_test_db() -> None:
    admin_engine = sqlalchemy.create_engine(ADMIN_DATABASE_URL, isolation_level="AUTOCOMMIT")
    try:
        with admin_engine.connect() as conn:
            # WITH (FORCE) (Postgres 13+) disconnects any lingering
            # sessions instead of erroring "database is being accessed by
            # other users" — this fixture owns the database's full
            # lifecycle, so nothing else should legitimately be connected.
            conn.execute(sqlalchemy.text(f"DROP DATABASE IF EXISTS {MIGRATION_TEST_DB_NAME} WITH (FORCE)"))
            conn.execute(sqlalchemy.text(f"CREATE DATABASE {MIGRATION_TEST_DB_NAME}"))
    finally:
        admin_engine.dispose()


def _drop_migration_test_db() -> None:
    admin_engine = sqlalchemy.create_engine(ADMIN_DATABASE_URL, isolation_level="AUTOCOMMIT")
    try:
        with admin_engine.connect() as conn:
            conn.execute(sqlalchemy.text(f"DROP DATABASE IF EXISTS {MIGRATION_TEST_DB_NAME} WITH (FORCE)"))
    finally:
        admin_engine.dispose()


@pytest.fixture()
def migration_test_db_url():
    _drop_and_create_migration_test_db()
    try:
        yield MIGRATION_TEST_DATABASE_URL
    finally:
        _drop_migration_test_db()


def _alembic_config(database_url: str) -> Config:
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(ALEMBIC_SCRIPT_LOCATION))
    config.set_main_option("sqlalchemy.url", database_url)
    return config


def test_alembic_upgrade_head_has_no_drift_against_models(migration_test_db_url):
    config = _alembic_config(migration_test_db_url)

    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "alembic upgrade head produced a schema that disagrees with "
            f"koshi.db.Base's models (a migration is missing or out of "
            f"sync with a model change): {exc}"
        )
